/**
 * Copyright 2022 F5 Networks, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

'use strict';

const assert = require('assert');
const buildProtectedObj = require('../../src/util/convert/buildProtectedObj');
const convertToNameValueObj = require('../../src/util/convert/convertToNameValueObj');
const declarationBase = require('../../src/util/convert/declarationBase');
const dedupeArray = require('../../src/util/convert/dedupeArray');
const deleteProperty = require('../../src/util/convert/deleteProperty');
const enabledToEnable = require('../../src/util/convert/enabledToEnable');
const findLocation = require('../../src/util/convert/findLocation');
const formatStr = require('../../src/util/convert/formatStr');
const getCidrFromNetmask = require('../../src/util/convert/getCidrFromNetmask');
const getMergedAS3Properties = require('../../src/util/getMergedAS3Properties');
const getObjectType = require('../../src/util/convert/getObjectType');
const handleObjectRef = require('../../src/util/convert/handleObjectRef');
const hyphensToCamel = require('../../src/util/convert/hyphensToCamel');
const isInteger = require('../../src/util/convert/isInteger');
const isIPv4 = require('../../src/util/convert/isIPv4');
const isIPv6 = require('../../src/util/convert/isIPv6');
const prependObjProps = require('../../src/util/convert/prependObjProps');
const recursiveCamelize = require('../../src/util/convert/recursiveCamelize');
const returnEmptyObjIfNone = require('../../src/util/convert/returnEmptyObjIfNone');
const unquote = require('../../src/util/convert/unquote');

describe('Converter utils (util/convert)', () => {
    describe('buildProtectedObject', () => {
        it('should build from a protected property', () => {
            const input = 'f5f5'.toString('base64');
            const output = buildProtectedObj(input);
            const expected = {
                ciphertext: 'ZjVmNQ==',
                protected: 'eyJhbGciOiJkaXIiLCJlbmMiOiJub25lIn0=',
                ignoreChanges: true
            };
            assert.deepStrictEqual(expected, output);
        });

        it('should build from an unprotected property', () => {
            const input = '$M$f5f5enctext'.toString('base64');
            const output = buildProtectedObj(input);
            const expected = {
                ciphertext: 'JE0kZjVmNWVuY3RleHQ=',
                protected: 'eyJhbGciOiJkaXIiLCJlbmMiOiJmNXN2In0=',
                ignoreChanges: true
            };
            assert.deepStrictEqual(expected, output);
        });
    });

    describe('convertToNameValueObj', () => {
        it('should convert a string to object', () => {
            const input = '"foo: bar"';
            const output = convertToNameValueObj(input);
            assert.deepStrictEqual({ name: 'foo', value: 'bar' }, output);
        });

        it('should convert an actual value', () => {
            const input = '"ip: IP::remote_addr"';
            const output = convertToNameValueObj(input);
            assert.deepStrictEqual({ name: 'ip', value: 'IP::remote_addr' }, output);
        });

        it('should handle an "empty" value', () => {
            const input = 'X-Header-Insert:';
            const output = convertToNameValueObj(input);
            assert.deepStrictEqual({ name: 'X-Header-Insert', value: '' }, output);
        });
    });

    describe('declarationBase', () => {
        describe('.AS3', () => {
            it('should return the base json', () => {
                const output = declarationBase.AS3();
                assert.strictEqual('ADC', output.class);
                assert.strictEqual('Converted Declaration', output.label);
                assert.strictEqual('Generated by Automation Config Converter', output.remark);
            });

            it('should optionally add the controls stanza', () => {
                const output = declarationBase.AS3({ controls: true });
                const expected = {
                    class: 'Controls',
                    trace: true,
                    logLevel: 'debug'
                };
                assert.deepStrictEqual(expected, output.controls);
            });
        });

        describe('.DO', () => {
            it('should return the base json', () => {
                const output = declarationBase.DO();
                assert.strictEqual('Device', output.class);
                assert(output.async);
            });

            it('should optionally add the controls stanza', () => {
                const output = declarationBase.DO({ controls: true });
                assert.strictEqual('Controls', output.controls.class);
                assert(output.controls.userAgent.includes('F5-AUTOMATION-CONFIG-CONVERTER'));
                assert(output.controls.trace);
                assert(output.controls.traceResponse);
                assert(!output.controls.dryRun);
            });
        });
    });

    describe('dedupeArray', () => {
        it('should remove duplicate strings', () => {
            const input = ['hi', 'test', 'str', 'hi'];
            const output = dedupeArray(input);
            assert.deepStrictEqual(['hi', 'test', 'str'], output);
        });

        it('should remove duplicate ref objects', () => {
            const input = [{ use: 'test' }, { use: 'another' }, { use: 'test' }];
            const output = dedupeArray(input);
            assert.deepStrictEqual([{ use: 'test' }, { use: 'another' }], output);
        });

        it('should handle both simultaneously', () => {
            const input = ['hi', { use: 'test' }, '3', 'hi', { use: 'the' }, { use: 'test' }];
            const output = dedupeArray(input);
            assert.deepStrictEqual(['hi', { use: 'test' }, '3', { use: 'the' }], output);
        });
    });

    describe('enabledToEnable', () => {
        it('should handle "enabled"', () => {
            const input = 'enabled';
            const output = enabledToEnable(input);
            assert.strictEqual('enable', output);
        });

        it('should handle "disabled"', () => {
            const input = 'disabled';
            const output = enabledToEnable(input);
            assert.strictEqual('disable', output);
        });

        it('should not handle anything else', () => {
            const input = 'auto';
            const output = enabledToEnable(input);
            assert.strictEqual('auto', output);
        });
    });

    describe('findLocation', () => {
        it('should split the BIG-IP path', () => {
            const input = '/Tenant1/App1/Profile1';
            const output = findLocation(input);
            const expected = {
                app: 'App1',
                iapp: false,
                original: '/Tenant1/App1/Profile1',
                profile: 'Profile1',
                tenant: 'Tenant1'
            };
            assert.deepStrictEqual(expected, output);
        });

        // AS3 supports '.' and '-' in names and pathes since v3.17.1
        it('should save chars ._-', () => {
            const input = '/Te_nan.t1/App-1/Prof.ile1';
            const output = findLocation(input);
            const expected = {
                app: 'App-1',
                iapp: false,
                original: '/Te_nan.t1/App-1/Prof.ile1',
                profile: 'Prof.ile1',
                tenant: 'Te_nan.t1'
            };
            assert.deepStrictEqual(expected, output);
        });
    });

    describe('formatStr', () => {
        it('should trim path to 194 symbols', () => {
            const input = '/AS3_Tenant_longer_than_48wwwwwwwwwwwwwwwwwwwwwwwwww/AS3_Application_longer_than_48wwwwwwwwwwwwwwwwwwwwwwwwww/Profile_name_longer_than_194qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqaaaa';
            const output = formatStr(input);
            assert.strictEqual('/AS3_Tenant_longer_than_48wwwwwwwwwwwwwwwwwwwwwwwwww/AS3_Application_longer_than_48wwwwwwwwwwwwwwwwwwwwwwwwww/Profile_name_longer_than_194qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq', output);
        });

        it('should return 3rd element as object name if name not quoted', () => {
            const input = 'ltm vurtual /AS3_Tenant_longer_than_48wwwwwwwwwwwwwwwwwwwwwwwwww/AS3_Application_longer_than_48wwwwwwwwwwwwwwwwwwwwwwwwww/Profile_name_longer_than_194qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqaaaa';
            const output = formatStr(input);
            assert.strictEqual('/AS3_Tenant_longer_than_48wwwwwwwwwwwwwwwwwwwwwwwwww/AS3_Application_longer_than_48wwwwwwwwwwwwwwwwwwwwwwwwww/Profile_name_longer_than_194qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq', output);
        });
        it('should replace spaces with _ if profile name quoted', () => {
            const input = 'ltm vurtual "/AS3_Tenant_longer_than_48wwwwwwwwwwwwwwwwwwwwwwwwww/AS3_Application_longer_than_48wwwwwwwwwwwwwwwwwwwwwwwwww/Profile_name_longer_than_194 with spaces qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqaaaa"';
            const output = formatStr(input);
            assert.strictEqual('/AS3_Tenant_longer_than_48wwwwwwwwwwwwwwwwwwwwwwwwww/AS3_Application_longer_than_48wwwwwwwwwwwwwwwwwwwwwwwwww/Profile_name_longer_than_194_with_spaces_qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq', output);
        });

        it('should remove leading _', () => {
            const input = 'ltm vurtual "/AS3_Tenant_longer_than_48wwwwwwwwwwwwwwwwwwwwwwwww/AS3_Application_longer_than_48wwwwwwwwwwwwwwwwwwwwwwwwww/_Profile_name_longer_than_194 with spaces qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqaaaa"';
            const output = formatStr(input);
            assert.strictEqual('/AS3_Tenant_longer_than_48wwwwwwwwwwwwwwwwwwwwwwwww/AS3_Application_longer_than_48wwwwwwwwwwwwwwwwwwwwwwwwww/_Profile_name_longer_than_194_with_spaces_qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq', output);
        });
    });

    describe('getCidrFromNetmask', () => {
        it('should convert netmask to cidr', () => {
            const input = '255.255.240.0';
            const output = getCidrFromNetmask(input);
            assert.strictEqual('/20', output);
        });

        it('should convert with noSlash option', () => {
            const input = '255.240.0.0';
            const output = getCidrFromNetmask(input, true);
            assert.strictEqual(12, output);
        });
    });

    describe('getObjectType', () => {
        it('should return the correct object type', () => {
            const input = { 'ltm profile http /AS3_Tenant/AS3_Application/webtls': {} };
            const output = getObjectType('/AS3_Tenant/AS3_Application/webtls', input);
            assert.strictEqual('http', output);
        });

        it('should only work on ltm objects', () => {
            const input = { 'analytics gui-widget /Common/12345678910': {} };
            const output = getObjectType('/Common/12345678910', input);
            assert.strictEqual(false, output);
        });
    });

    describe('handleObjectRef', () => {
        it('should recognize default objects', () => {
            const input = '/Common/http';
            const output = handleObjectRef(input);
            assert.deepStrictEqual({ bigip: '/Common/http' }, output);
        });

        it('should handle custom objects', () => {
            const input = '/Common/custom_thing';
            const output = handleObjectRef(input);
            assert.deepStrictEqual({ use: '/Common/Shared/custom_thing' }, output);
        });
    });

    describe('hyphensToCamel', () => {
        it('should convert from hyphen-case to camelCase', () => {
            const input = 'example-string-here';
            const output = hyphensToCamel(input);
            assert.strictEqual('exampleStringHere', output);
        });
    });

    describe('isInteger', () => {
        it('should return true if integer', () => {
            const input = 12345;
            const output = isInteger(input);
            assert.strictEqual(true, output);
        });

        it('should return true if stringified integer', () => {
            const input = '12345';
            const output = isInteger(input);
            assert.strictEqual(true, output);
        });

        it('should return false if true string', () => {
            const input = '1a2b3c';
            const output = isInteger(input);
            assert.strictEqual(false, output);
        });
    });

    describe('isIPv4', () => {
        it('should return true if ipv4', () => {
            const input = '192.168.1.1';
            const output = isIPv4(input);
            assert.strictEqual(true, output);
        });

        it('should handle ipv4 with port', () => {
            const input = '1.1.1.1:1';
            const output = isIPv4(input);
            assert.strictEqual(true, output);
        });

        it('should return false if ipv6', () => {
            const input = 'fdf5:4153:3300::15.0';
            const output = isIPv4(input);
            assert.strictEqual(false, output);
        });
    });

    describe('isIPv6', () => {
        it('should return true if ipv6', () => {
            const input = 'fdf5:4153:3300::15';
            const output = isIPv6(input);
            assert.strictEqual(true, output);
        });

        it('should handle ipv6 with port', () => {
            const input = 'fdf5:4153:3300::15.0';
            const output = isIPv6(input);
            assert.strictEqual(true, output);
        });

        it('should return false if ipv4', () => {
            const input = '192.168.1.1:80';
            const output = isIPv6(input);
            assert.strictEqual(false, output);
        });
    });

    describe('prependObjProps', () => {
        it('should work for hsts, but not enforcement', () => {
            const input = {
                includeSubdomains: true,
                period: 7862400,
                insert: false,
                preload: false
            };
            const output = prependObjProps(input, 'hsts');
            const expected = {
                hstsIncludeSubdomains: true,
                hstsPeriod: 7862400,
                hstsInsert: false,
                hstsPreload: false
            };
            assert.deepStrictEqual(expected, output);
        });
    });

    describe('recursiveCamelize', () => {
        it('should convert keys in all included objects to camelCase', () => {
            const input = { 'test-key': { 'test-sub-key': true, 'second.key': false } };
            const output = recursiveCamelize(input);
            const expected = { testKey: { testSubKey: true, 'second.key': false } };
            assert.deepStrictEqual(expected, output);
        });
    });

    describe('returnEmptyObjIfNone', () => {
        it('should return empty if the property is "none"', () => {
            const input = { test: 'none' };
            const output = returnEmptyObjIfNone(input.test, input);
            assert.deepStrictEqual({}, output);
        });

        it('should otherwise return in original input', () => {
            const input = { test: 'test test' };
            const output = returnEmptyObjIfNone(input.test, input);
            assert.deepStrictEqual(input, output);
        });
    });

    describe('unquote', () => {
        it('should unquote a string', () => {
            const input = '"Test string"';
            const output = unquote(input);
            assert.strictEqual('Test string', output);
        });

        it('should unquote a single-quote string', () => {
            const input = "'Test string'";
            const output = unquote(input);
            assert.strictEqual('Test string', output);
        });

        it('should unquote a tilde-quote string', () => {
            const input = '`Test string`';
            const output = unquote(input);
            assert.strictEqual('Test string', output);
        });

        it('should not remove other characters', () => {
            const input = 'Test string';
            const output = unquote(input);
            assert.strictEqual('Test string', output);
        });
    });

    describe('Merging recognized properties (getMergedAS3Properties.js)', () => {
        it('Should merge properties.json with as3PropertiesCustom.json', () => {
            const mergedAS3Properties = getMergedAS3Properties();
            // 'gtm monitor http' not found in properties.json
            assert(mergedAS3Properties['gtm monitor http']);
            // 'ltm virtual' only found in properties.json
            assert(mergedAS3Properties['ltm virtual']);
        });
    });

    describe('Delete property by path (deleteProperty.js)', () => {
        it('Should delete properties', () => {
            const input = { a: [{ key: 'true' }, { key2: 'false' }], b: 10 };
            const property = '/a/1/key2';
            deleteProperty(input, property);
            assert.deepEqual({ a: [{ key: 'true' }], b: 10 }, input);
        });

        it('Should delete properties and clean up empty objects', () => {
            const input = { a: [{ key: 'true' }], b: 10 };
            const property = '/a/0';
            deleteProperty(input, property);
            assert.deepEqual({ b: 10 }, input);
        });

        it('Should delete properties and clean up difficult objects', () => {
            const input = { a: 'testA', b: { b_1: { value: 'test_value' }, b_2: { value: 'test_value' } } };
            const property1 = '/b/b_1/value';
            const property2 = '/b/b_2/value';
            deleteProperty(input, property1);
            deleteProperty(input, property2);
            assert.deepEqual({ a: 'testA' }, input);
        });
    });
});
